# uv/uvx shell completions
_dot_shell="bash"
[ -n "${ZSH_VERSION:-}" ] && _dot_shell="zsh"
command -v uv &>/dev/null && eval "$(uv generate-shell-completion "$_dot_shell")"
command -v uvx &>/dev/null && eval "$(uvx --generate-shell-completion "$_dot_shell")"
unset _dot_shell

# bash-completion scripts and `complete` are bash-only; zsh has neither.
if [ -n "${BASH_VERSION:-}" ]; then
    # shellcheck source=/dev/null  # optional, generated by each tool's installer
    for _dot_comp in \
        "$HOME/.bash-completion/completions/task.bash" \
        "$HOME/.local/share/bash-completion/completions/k3d/k3d_completion.sh"; do
        [ -f "$_dot_comp" ] && source "$_dot_comp"
    done
    unset _dot_comp

    # terraform completion
    command -v terraform &>/dev/null && complete -C "$HOME/.local/bin/terraform" terraform
fi
