#!/usr/bin/env bash
# Generate internal/ui/theme_gen.go from design/palette.toml, so a flavor is
# defined in exactly one place. The sidebar used to hold its own hand-synced copy
# of the hex values, which would drift silently on the next palette edit.
#
# Run by the Makefile before build and test. The output is committed, so
# `go build` works without running this first.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
PALETTE="${THEME_PALETTE:-$REPO/design/palette.toml}"
OUT="${THEME_GEN_OUT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/internal/ui/theme_gen.go}"

# flavor -> Go constructor name.
FLAVORS="solarized-light:SolarizedLight
solarized-dark:SolarizedDark
catppuccin-latte:CatppuccinLatte
catppuccin-mocha:CatppuccinMocha
catppuccin-mocha-black:CatppuccinMochaBlack"

# The default flavor is palette.toml's [meta] default, never a name repeated here -
# a fork shipping a different default must not have to patch this script.
DEFAULT_FLAVOR=$(awk '
    /^\[/ { in_s = ($0 == "[meta]") }
    in_s && $1 == "default" && !found { gsub(/"/, "", $3); print $3; found = 1 }
' "$PALETTE")
DEFAULT_FN=$(printf '%s\n' "$FLAVORS" |
    awk -F: -v f="$DEFAULT_FLAVOR" '$1 == f && !found { print $2; found = 1 }')
[ -n "$DEFAULT_FN" ] || {
    echo "gen-theme: [meta] default '$DEFAULT_FLAVOR' is not a known flavor" >&2
    exit 1
}

get() { # get <flavor> <key>
    awk -v want="[themes.$1]" -v key="$2" '
        /^\[/ { in_s = ($0 == want) }
        in_s && $1 == key { gsub(/"/, "", $3); print $3; exit }
    ' "$PALETTE"
}

tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT

{
    echo "// Code generated by scripts/gen-theme.sh from design/palette.toml. DO NOT EDIT."
    echo
    echo "package ui"
    echo
    while IFS=: read -r flavor fn; do
        [ -n "$flavor" ] || continue
        echo "// $fn is the $flavor flavor."
        echo "func $fn() Theme {"
        echo "	return Theme{"
        # Struct field <- palette key. SelBg is the one that is not a name match.
        printf '\t\tFg:       "%s",\n' "$(get "$flavor" fg)"
        printf '\t\tMuted:    "%s",\n' "$(get "$flavor" muted)"
        printf '\t\tEmphasis: "%s",\n' "$(get "$flavor" emphasis)"
        printf '\t\tAccent:   "%s",\n' "$(get "$flavor" accent)"
        printf '\t\tSelBg:    "%s",\n' "$(get "$flavor" selection)"
        printf '\t\tWorking:  "%s",\n' "$(get "$flavor" working)"
        printf '\t\tAsking:   "%s",\n' "$(get "$flavor" asking)"
        printf '\t\tBlocked:  "%s",\n' "$(get "$flavor" blocked)"
        printf '\t\tDone:     "%s",\n' "$(get "$flavor" "done")"
        echo "	}"
        echo "}"
        echo
    done <<<"$FLAVORS"

    echo "// ThemeByName resolves a flavor name, falling back to the default flavor."
    echo "func ThemeByName(name string) Theme {"
    echo "	switch name {"
    while IFS=: read -r flavor fn; do
        [ -n "$flavor" ] || continue
        [ "$flavor" = "$DEFAULT_FLAVOR" ] && continue # it is the default arm
        printf '\tcase "%s":\n\t\treturn %s()\n' "$flavor" "$fn"
    done <<<"$FLAVORS"
    echo "	default:"
    echo "		return $DEFAULT_FN()"
    echo "	}"
    echo "}"
} >"$tmp"

gofmt -w "$tmp" 2>/dev/null || true
if [ -f "$OUT" ] && cmp -s "$tmp" "$OUT"; then
    exit 0 # unchanged: keep the mtime so make does not rebuild for nothing
fi
mv "$tmp" "$OUT"
trap - EXIT
